### ISSUE TITLE
No login with GitHub connector

### ISSUE THREAD

**Issue by JbIPS** [silexlabs/cloud-explorer#54]
Hello @zabojad, I'm trying to add a new GitHub connector but I'm facing an issue after login: the iframe doesn't reload to show the files. If I close the frame and reopen it, my files show up and everything's fine.

@lexoyo targeted the issue [here](https://github.com/silexlabs/unifile/issues/41) but I don't know why the parameter is `undefined` here. Do you have any leads? Thanks.

**Comment by zabojad** [comment]
Hey @JbIPS ! I have no idea about that... Can you post some jsfliddle link or equivalent so that I see better about what you are talking about ?

**Comment by JbIPS** [comment]
I'd like to, but I don't think I can use them with CE and Unifile, or can you tell me how? 
On the other hand, you can reproduce it by using the head of master on Unifile but I understand this can be more complicated for you ^^

**Comment by JbIPS** [comment]
Actually, maybe I can make it a bit clearer now.
Here is what happen:
* After OAuth connection, GitHub call back the URL I gave it (`/api/v1.0/github-auth`)
* This call is handled [here](https://github.com/silexlabs/unifile/blob/master/lib/services/github.js#L284) and open a [pop-up, as for FTP login](https://github.com/silexlabs/unifile/blob/master/lib/templates/login-ftp.jade) with a parameter `success` to `true`
* This pop-up automatically closes which trigger [application.onServiceAuthorizationDone](https://github.com/silexlabs/cloud-explorer/blob/master/src/ce/core/Controller.hx#L1063) on CE because of the [timer](https://github.com/silexlabs/cloud-explorer/blob/8055aa0397181c97bd6f6509a0109ea4171adce3/src/ce/core/view/Application.hx#L315) checking the pop-up closure. 
* But in this case, the function is called without parameter thus failing [the test](https://github.com/silexlabs/cloud-explorer/blob/master/src/ce/core/Controller.hx#L1069) and not refreshing the window.

And checked a bit how the Dropbox connector is doing and it's almost the same workflow but the pop-up is not the same. Dropbox is calling [oauth-cb.html](https://github.com/silexlabs/cloud-explorer/blob/8055aa0397181c97bd6f6509a0109ea4171adce3/app/oauth-cb.html) which is calling the same function but with `window.location.search` as a parameter, thus refreshing the window.

I'm not very clear on why it's taking a different path so any clue to unblur this will be welcomed :)

**Comment by zabojad** [comment]
Just re-read the code and Dropbox calls oauth-cb.html because we give it the instruction to do so [when opening the authorization popup](https://github.com/silexlabs/cloud-explorer/blob/8055aa0397181c97bd6f6509a0109ea4171adce3/src/ce/core/Controller.hx#L1084).

So now, why Github isn't doing the same? Is it the same version of oAuth? Does it support to be given a callback url? If yes, what is the way to pass it the cb page url?

**Comment by JbIPS** [comment]
The callback URL on GitHub has to be given when registering the application. Your saying that giving it server/oauth-cb.html as URL will fix the problem?

**Comment by zabojad** [comment]
What I'm saying is that the callback url has a point with the version of oauth Dropbox uses. It's the way CE knows if the use of the Dropbox service for CE has been approved by the user. I guess it should work the same way with Github's oauth... What happens when you try to set server/oauth-cb.html as the cb url for your Github app ?

**Comment by JbIPS** [comment]
GitHub is expecting an endpoint where it can send me a token for the session. So if I use oauth-cb.html as callback I get 
```
Cannot GET /libs/cloud-explorer/oauth_cb.html?code=XXXXXXXX
```
Is there a way to 'simulate' what this popup is doing?
